# Generated by Django 2.2.5 on 2019-12-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0002_sauvegarde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
    ]
